# WhatATheme
markdown: kramdown

# URL of the Site
url: 'https://builtwithruby.com'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: ''
host: 0.0.0.0

# Title of the Site
title: "#BuiltWithRuby | Built With Ruby"
# Description of the Site
description: Let's make Ruby Great again.
# URL of Image of the Site
site-image: /assets/images/bwr-banner.png
# Keywords of the Site
site-keywords: Ruby, Rails, BuiltWithRuby
# URL for the Image of custom Favicon
favicon-url: /assets/images/favicon.ico

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: gkunwar09@gmail.com
facebook_username: gkunwar1
twitter_username: gkunwar1
instagram_username: gkunwar1
linkedin_username: gkunwar1
github_username:  gkunwar
youtube_channel_id: 
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
# permalink: "blog/:title"

# Compress
compress_html:
  clippings: all


# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
